// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousMotionProfile.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutonomousMotionProfile::AutonomousMotionProfile(): Command(),
talonService(Robot::driveTrain->ServiceMotionProfile()) {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutonomousMotionProfile::Initialize() {
	if (mRightWheel) {
		Robot::driveTrain->FillProfileBuffer(mLeftWheel, mRightWheel);
	}
	else {
		Robot::driveTrain->FillProfileBuffer(mLeftWheel);
	}
}

// Called repeatedly when this Command is scheduled to run
void AutonomousMotionProfile::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousMotionProfile::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void AutonomousMotionProfile::End() {

}


// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousMotionProfile::Interrupted() {

}

AutonomousMotionProfile::AutonomousMotionProfile(const ProfileData* LeftWheel) : Command(),
		talonService(Robot::driveTrain->ServiceMotionProfile()){
	Requires(Robot::driveTrain.get());
	mLeftWheel.reset(LeftWheel);
	mRightWheel.reset();
}

AutonomousMotionProfile::AutonomousMotionProfile(const ProfileData* LeftWheel,
		const ProfileData* RightWheel) : Command(),
				talonService(Robot::driveTrain->ServiceMotionProfile()) {
	Requires(Robot::driveTrain.get());
	mLeftWheel.reset(LeftWheel);
	mRightWheel.reset(RightWheel);
}
