// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoonomousFireBoulderHigh.h"
#include "ShooterFlywheelHigh.h"
#include "ShooterFlywheelReverse.h"
#include "ShooterFlywheelStop.h"
#include "ShooterKickBall.h"


#define REVERSE_TIME 0.3f
#define STOP_TIME 0.25f
#define HS_SPIN_TIME 0.75f
#define LAUNCH_TIME 0.75f

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoonomousFireBoulderHigh::AutoonomousFireBoulderHigh() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
	AddSequential(new ShooterFlywheelReverse(REVERSE_TIME));
	AddSequential(new ShooterFlywheelStop(STOP_TIME));
	AddSequential(new ShooterFlywheelHigh(HS_SPIN_TIME));
	AddSequential(new ShooterKickBall(LAUNCH_TIME));
	AddSequential(new WaitCommand(LAUNCH_TIME));
	AddSequential(new ShooterFlywheelStop());
}
