// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CLIMBER_H
#define CLIMBER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Climber: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<SpeedController> hookMotor;
	std::shared_ptr<DigitalInput> hookRearMax;
	std::shared_ptr<DigitalInput> hookMax;
	std::shared_ptr<DigitalInput> hookHome;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	const float kHookRaiseSpeed = 1.0;
	const float kHookLowerSpeed = -0.75;
	const float kHookStop = 0.0;

public:
	Climber();
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// Hook Manipulation public functions
	void HookRaise();
	void HookLower();
	void HookStop();
	bool HookIsHome();
	bool HookAtMax();
	bool HookAtRearMax();


};

#endif
