// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::chassisCANTalon1;
std::shared_ptr<CANTalon> RobotMap::chassisCANTalon2;
std::shared_ptr<RobotDrive> RobotMap::chassisRobotDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    chassisCANTalon1.reset(new CANTalon(1));
    lw->AddActuator("Chassis", "CAN Talon 1", chassisCANTalon1);
    
    chassisCANTalon2.reset(new CANTalon(2));
    lw->AddActuator("Chassis", "CAN Talon 2", chassisCANTalon2);
    
    chassisRobotDrive.reset(new RobotDrive(chassisCANTalon1, chassisCANTalon2));
    
    chassisRobotDrive->SetSafetyEnabled(true);
        chassisRobotDrive->SetExpiration(0.1);
        chassisRobotDrive->SetSensitivity(0.5);
        chassisRobotDrive->SetMaxOutput(1.0);

        chassisRobotDrive->SetInvertedMotor(RobotDrive::kRearRightMotor, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
